src/artGallery/urls.py
from django.urls import path
from .views import home, add_to_cart, art_detail
app_name = "artGallery"
urlpatterns = [
    path("", home, name="home"),
    path("add-to-cart", add_to_cart, name="add-to-cart"),
    path("art-detail/<int:art_id>", art_detail, name="art-detail")

]

src/cart/urls.py
from django.urls import path
from .views import view_art_gallery_cart, exhibition_cart, choose_cart
app_name = "cart"
urlpatterns = [
    path("", choose_cart, name="cart"),
    path("exhibition-cart", exhibition_cart, name="exhibition-cart"),
    path("art-gallery-cart", view_art_gallery_cart, name="art-gallery-cart")
]

src/client/urls.py
from django.urls import path
from .views import dashboard, update_client_or_artist, add_art, profile, client_profile, artist_profile, view_artist_profile
app_name = "client"
urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("client-update", update_client_or_artist, name="client-update"),
    path("add-art", add_art, name="add-art"),
    path("client-profile", client_profile, name="client-profile"),
    path("artist-profile", artist_profile, name="artist-profile"),
    path("view-artist-profile/<str:artist_id>",
         view_artist_profile, name="view-artist-profile"),
    path("profile", profile, name="profile")
]

src/online_art_gallery/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from .view import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home_view, name="home"),
    # for signup and login feature
    path("authentication/", include("authentication.urls")),
    # for artGallery
    path("artgallery/", include("artGallery.urls")),
    path("dashboard/", include(("client.urls"))),
    path("exhibition/", include("exhibition.urls")),
    path("search/", include("search.urls"),),
    path("cart/", include("cart.urls")),

]

# this make the static file to load when were they are requested from url
urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/client/models.py
from django.db import models
from django.contrib.auth.models import User
from cart.models import cart
from artGallery.models import art
from django.template.defaultfilters import slugify

# Create your models here.


class client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=False)
    first_name = models.CharField(max_length=32, blank=True)
    last_name = models.CharField(max_length=32, blank=True)
    profile_photo = models.ImageField(
        default="profile.png", upload_to='profile/')
    bio = models.CharField(max_length=200, default="no bio...")
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, blank=True, null=True, editable=False)
    is_client = models.BooleanField(choices=[(True, "yes"), ], default=True)
    mycart = models.OneToOneField(
        cart, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}-{self.date_created.strftime('%d-%m-%Y')}"

    def save(self, *args, **kargs):
        self.slug = slugify(str(self.user.username))
        super().save(*args, **kargs)

    def get_user_email(self):
        return self.user.email


class artist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=False)
    art_list = models.ManyToManyField(
        art, blank=True, null=True)
    first_name = models.CharField(max_length=32, blank=True)
    last_name = models.CharField(max_length=32, blank=True)
    profile_photo = models.ImageField(
        default="profile.png", upload_to='profile/')
    bio = models.CharField(max_length=200, default="no bio...")
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    is_artist = models.BooleanField(choices=[(True, "Yes"), ], default=True)

    def __str__(self):
        return f"{self.user.username}-{self.date_created.strftime('%d-%m-%Y')}"

    def save(self, *args, **kargs):
        self.slug = slugify(str(self.user.username))
        super().save(*args, **kargs)

    def get_user_email(self):
        return f"{self.user.email}"

src/client/forms.py
from django.forms import ModelForm
from django import forms
from .models import client, artist


class client_update_form(ModelForm):

    bio = forms.CharField(widget=forms.Textarea(attrs={"rows": "2"}))

    class Meta:
        model = client
        fields = ["profile_photo", "bio", "first_name", "last_name"]

    # def save(self, commit=False):
    #     user = self.instance
    #     user.bio = self.cleaned_data["bio"]
    #     user.profile_photo = self.cleaned_data["profile_photo"]
    #     user.first_name = self.cleaned_data["first_name"]
    #     user.last_name = self.cleaned_data["last_name"]
    #     user.save()
    #     return user


class artist_update_form(ModelForm):

    class Meta:
        model = artist
        fields = ["profile_photo", "bio", "first_name", "last_name"]

src/client/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect
from .models import client, artist
from .forms import client_update_form, artist_update_form
from artGallery.forms import art_add_or_update
from artGallery.models import art
from django.contrib.auth.models import User
# Create your views here.


def view_artist_profile(request, artist_id):
    user = request.user
    if(not(user.is_authenticated) or request.user.is_superuser):
        return render(request, "client/not-found.html", context={
            "error": "you must login as client or artist first"
        })
    else:
        if request.method == "GET":
            user = User.objects.filter(username=str(artist_id)).first()

            if(user):
                current_artist = artist.objects.filter(user=user).first()
                if(current_artist):
                    artist_arts = [(art, art.artist_set.all().first())
                                   for art in current_artist.art_list.all().order_by('-date_created')[:10]]
                    context = {
                        "artist": current_artist,
                        "recent_arts":  artist_arts,
                        "total_recent_arts": len(artist_arts)
                    }
                    return render(request, "client/artist-profile.html", context)
                else:
                    return render(request, "client/not-found.html", {"error": "artist  not found"})


def dashboard(request):
    user = request.user
    if(not(user.is_authenticated) or request.user.is_superuser):
        return render(request, "client/not-found.html", context={
            "error": "you must login as client or artist first"
        })
    else:
        current_client = client.objects.filter(user=request.user).first()
        if(current_client):
            if(current_client.mycart):
                # arts = list(current_client.mycart.art_list.all())
                arts = [(art, art.artist_set.all().first())
                        for art in current_client.mycart.art_list.all()]
            else:
                arts = []
            context = {
                "client": current_client,
                "arts":  arts
            }
            return render(request, "client/client-dashboard.html", context)
        else:
            current_artist = artist.objects.filter(user=request.user).first()
            arts = [(art, art.artist_set.all().first())
                    for art in current_artist.art_list.all()]
            context = {
                "artist": current_artist,
                "arts": arts
            }
            return render(request, "client/artist-dashboard.html", context)


def profile(request):
    """
    view profile of user or artist
    """
    user = request.user
    if(not(user.is_authenticated) or request.user.is_superuser):
        return render(request, "client/not-found.html", context={
            "error": "you must login as client or artist first"
        })
    else:
        current_artist = artist.objects.filter(user=request.user).first()
        if(current_artist):
            return artist_profile(request)
        else:
            return client_profile(request)


def artist_profile(request):
    user = request.user
    if(not(user.is_authenticated) or request.user.is_superuser):
        return render(request, "client/not-found.html", context={
            "error": "you must login as client or artist first"
        })
    else:
        current_artist = artist.objects.filter(user=request.user).first()
        if(current_artist):
            artist_arts = [(art, art.artist_set.all().first())
                           for art in current_artist.art_list.all().order_by('-date_created')[:10]]
            context = {
                "artist": current_artist,
                "recent_arts":  artist_arts,
                "total_recent_arts": len(artist_arts)
            }
            return render(request, "client/artist-profile.html", context)
        else:
            return render(request, "client/not-found.html", {"error": "you are not artist"})


def client_profile(request):
    user = request.user
    if(not(user.is_authenticated) or request.user.is_superuser):
        return render(request, "client/not-found.html", context={
            "error": "you must login as client or artist first"
        })
    else:
        current_client = client.objects.filter(user=request.user).first()
        if(current_client):
            cart_arts = []
            if(current_client.mycart):
                # arts = list(current_client.mycart.art_list.all())
                cart_arts = [(art, art.artist_set.all().first())
                             for art in current_client.mycart.art_list.all()]
            else:
                arts = []
            context = {
                "client": current_client,
                "cart_arts":  cart_arts,
                "total_cart_arts": len(cart_arts)
            }
            return render(request, "client/client-profile.html", context)
        else:

            return render(request, "client/not-found.html", {"error": "you are not client"})


def update_client_or_artist(request):
    if(not(request.user.is_authenticated) or request.user.is_superuser):
        return render(request, "client/not-found.html", context={
            "error": "you must login as client or artist first"
        })

    if(not(request.user.is_authenticated)):
        return render(request, "client/not-found.html", context={
            "error": "you must login as client or artist first"
        })

    else:
        is_client_updated = False
        current_client = client.objects.filter(user=request.user).first()

        if(current_client):
            form = client_update_form(initial={
                "profile_photo": current_client.profile_photo,
                "first_name": current_client.first_name,
                "last_name": current_client.last_name,
                "bio": current_client.bio
            })
            if(request.method == "POST"):
                instace_client = get_object_or_404(client, user=request.user)
                form = client_update_form(
                    request.POST, request.FILES, instance=instace_client)
                if form.is_valid():
                    valid_client = form.save(commit=False)
                    valid_client.save()
                    is_client_updated = True
                    return redirect("client:client-profile")
                else:
                    return HttpResponse("client not updated")
            context = {
                "form": form,
                "client": current_client,
                "is_updated": is_client_updated,
            }

            return render(request, "client/update-client.html", context)

        else:
            is_artist_updated = False
            current_artist = artist.objects.filter(user=request.user).first()

            if(current_artist):
                form = artist_update_form(initial={
                    "profile_photo": current_artist.profile_photo,
                    "first_name": current_artist.first_name,
                    "last_name": current_artist.last_name,
                    "bio": current_artist.bio
                })
            if(request.method == "POST"):
                instace_artist = get_object_or_404(artist, user=request.user)
                form = artist_update_form(
                    request.POST, request.FILES, instance=instace_artist)
                if form.is_valid():
                    valid_artist = form.save(commit=False)
                    valid_artist.save()

                    print(form.cleaned_data)

                    is_artist_updated = True
                    return redirect("client:artist-profile")
                else:
                    return HttpResponse("artist not updated")
            context = {
                "form": form,
                "artist": current_artist,
                "is_updated": is_artist_updated,
            }

            return render(request, "client/update-artist.html", context)


def add_art(request):
    if(not(request.user.is_authenticated) or request.user.is_superuser):
        return render(request, "client/not-found.html", context={
            "error": "you must login as client or artist first"
        })
    current_artist = artist.objects.filter(user=request.user).first()
    if(current_artist):
        is_new_art_added = False
        form = art_add_or_update()
        if(request.method == "POST"):
            form = art_add_or_update(
                request.POST, request.FILES)
            if form.is_valid():
                new_art = form.save()
                current_artist.art_list.add(new_art)
                is_new_art_added = True
                return redirect("client:artist-profile")
            else:
                print("invalid form")
        context = {
            "current_artist": current_artist,
            "form": form,
            "is_new_art_added": is_new_art_added,
        }
        return render(request, "client/add-art.html", context)
    else:
        context = {
            "error": "you must login as artist first"
        }
        return render(request, "client/not-found.html", context)

src/client/templates/client/add-art.html
{% extends 'base.html' %}

{% block title %}
{{request.user}}-add art
{% endblock title %}

{% block content %}
<div class="ui container">
<form action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
{{form}}
<button class="ui button primary" type="submit">add art</button>
</form>
</div>
{% endblock content %}

{% block scripts %}

<script>

$(document).ready(()=>{
$("form").addClass(["ui","form"])
$("form").children().filter("p").addClass("field")

});
</script>

{% endblock scripts %}

src/client/templates/client/artist-dashboard.html
{% extends 'base.html' %}
{% load humanize %}
{% block css %}
#social__container{
    position:relative;
}
#social__icons{
    position:absolute;
    bottom:10%;
}
 #m-small-top{
    margin-top:2rem;
} 
#profile__img{
    border-radius:50%;
}
{% endblock css %}
{% block title %}
{{request.user}}-dashboard
{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="row">
        <div class="ui three wide right floated column">
             <a class="ui button primary" href="{% url 'client:client-update' %}">
             <i class="edit outline icon"></i>
             Update Profile
             </a>
        </div>
    </div>
</div>

<div class="ui grid ">
    <div class="ui two column row horizontal segments">
        <div class="ui column segment">
            <div class="ui  grid ">
                {% comment %} for left postion of profile {% endcomment %}
                <div class="ui two column row">
                {% comment %} for image of profile {% endcomment %}
                    <div class="column">
                        <div class="ui grid">
                        <div class=" column three wide">
                        &nbsp;
                        </div>
                        <div class="ui column ten wide">
                          <svg width="168" height="168" style="">  
                            <defs>  
                            <mask id="text-mask-1" x="0" y="0" width="168" height="168">  
                                <circle cx="84" cy="84" fill="white" r="84"></circle>
                            </mask>  
                            </defs>
                            <circle cx="84" cy="84" fill="white" r="84" stroke="grey"></circle>
                            <image x="0" y="0" height="100%" preserveAspectRatio="slice" width="100%" xlink:href="{{MEDIA_URL}}{{artist.profile_photo}}" mask="url(#text-mask-1)"/>  
                        </svg>
                        </div>
                        <div class=" column three wide">
                        &nbsp;
                        </div>

                        </div>
                    </div>
                    {% comment %} for basic detail  of artist {% endcomment %}
                    <div class="column ">
                    <h1 class="ui header blue">{{artist.first_name|title|truncatechars:20}} {{artist.last_name|title|truncatechars:20}}</h1>
                    <h4 class="ui header orange"><i class="gift icon"></i>Art lover{{artist.one_word_about_me}}</h4>
                    <h2 class="ui  header green"><i class="icon flag"></i>Nepal{{artist.country}}</h2>
                    <h3 class="ui header blue"><a href = "mailto:{{artist.user.email}}"><i class="mail outline icon"></i>{{artist.user.email}}</a></h3>
                    </div>
                </div>
            </div>
        </div>
        {% comment %} for right bio and social of profile {% endcomment %}
        <div id="social__container" class="ui column segment">
        {% comment %} bio section {% endcomment %}
            <h1 class="ui centered header pink"><i class="heart icon"></i>My bio</h1>
            <h5 class="ui header centered"> {{artist.bio|truncatechars:100}}</h5>
        <div id="social__icons">
                    <div class="ui grid">
                    {% comment %} test {% endcomment %}
                    {% for account in artist.accounts %}
                    
                            <div class="two wide column">
                            <a href="{{account.link}}">
                            <i class="{{account.type}} icon"></i>
                            </a>
                            </div>
                            
                            {% empty %}
                            <div class="column"> <h5 class="ui header green">NO social media accounts</h5></div>
                            {% endfor %}
                    </div>
        </div>    
        </div>
    </div>
    <div id="m-small-top"class="row">
    <div class="ui top attached tabular menu">
        <div class="active item">
            <button id="my-cart" class="ui button primary active"> 
                <i class="icon theme"></i>my art
            </button>
        </div>
        <div class="item">
         <button id="my-cart" class="ui button basic primary "> 
                <i class="icon bookmark"></i>follower
         </button>
        </div>

    </div>
     <div class="ui bottom attached active tab segment">
     <div id="m-small-top" class="ui container">
       <a href="{% url 'client:add-art' %}"class="ui  button basic small pink">
        <i class="add square icon"></i>
        New Art
        </a>
     </div>
   
    <div id="m-small-top" class="ui container">
        <div  class="ui three column grid">
        {% for art,artist in arts %}
            <div class="column">
            {% include "client/card.html" %}
            </div>

            {% empty %}
            <div class="column">
            <h5 class="ui header yellow">no arts</h5>
            </div>
        
         {% endfor %}
    </div>
 </div>
</div>
        
    <div class="ui bottom attached  tab segment">
        {% for client in artist.follower  %}
        
        {% empty %}

        {% endfor %}
    </div>
   </div>
   </div>
 
    

{% endblock content %}

{% block scripts %}
<script>
jQuery(document).ready(($)=>{

})
</script>

{% endblock scripts %}

src/client/templates/client/artist-profile.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'client/artistProfile/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'new-navbar.css' %}">  
    <link rel="stylesheet" href="{% static 'style.css' %}"> 
    <link rel="stylesheet" href="{% static 'custom-buttons.css' %}">  

    <title>My profile</title>
</head>
<body>
{% include "main/new-navbar.html" %}
<section style="padding-top:80px;" class="profile">
  <header class="header">
    <div class="details">
       <a class="ui button primary" href="{% url 'client:client-update' %}">
      <img src="{{MEDIA_URL}}{{artist.profile_photo}}" alt="John Doe" class="profile-pic">
      </a>
      <h1 class="heading">{{request.user|truncatechars:20|title}}</h1>
      <div class="location">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
            <path d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12 ,2Z"></path>
        </svg>
        <p>Kathmandu, Nepal</p>
      </div>
      <div class="stats">
        <div class="col-4">
          <h4>{{total_recent_arts|intcomma}}</h4>
          <p>My Total Arts</p>
        </div>
        <div class="col-4">
          <h4>{{artist.date_updated|naturalday}}</h4>
          <p>Profile Updated</p>
        </div>
        <div class="col-4">
          <h4>{{artist.date_created|naturalday}}</h4>
          <p>Profile Created</p>
        </div>
      </div>
      <div class="bio">
      <p>
      {{artist.bio|truncatechars:200|lower}}
      </p>
      <h4>Bio</h4>
      </div>
    </div>
  </header>
</section>
<section>
<h1 class="title" style="color:pink;">Recent Arts</h1>
<section>
<div id="button">
<section class="buttons">
  <div class="container">
      <a href="{% url 'client:add-art' %}" class="btn btn-1">
      <svg>
        <rect x="0" y="0" fill="none" width="100%" height="100%"/>
      </svg>
     ADD MORE ARTS
    </a>
    </div>
</section>
</div>
</section>
<div id="app" class="container">
{% for art,artist in recent_arts %}
        <a href="{% url 'artGallery:art-detail' art.id %}">
        <card data-image="{{MEDIA_URL}}{{art.photo1}}">
            <h1 slot="header">{{art.art_name|truncatechars:6|title}}</h1>
            <p slot="content">{{art.art_name|truncatechars:20|lower}}</p>
        </card>
        </a>
{% endfor %}
</div>
</div>





</section> 

<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.0.1/vue.min.js"></script>
<script src="{% static 'client/artistProfile/js/main.js' %}"></script>
<script src="{% static 'main.js' %}"></script>  


</body>
</html>

src/client/templates/client/card.html
{% load humanize %}
<div id="c-card" class="ui card">
    <div id="c-card__pading"class="content">
    <img src="{{MEDIA_URL}}{{art.photo1}}" alt="" class="ui  image">
                
    <div id="c-card__top">
    <div id="margin-top-5 margin-bottom-5"><h5 class="ui header centered green label fluid">{{art.art_name|title}}</h5></div>
    <div class="ui grid middle aligned">
    <div class="row">
        <div class="eight wide column">
        <div class="ui small star rating" data-max-rating="5" data-rating="{{art.quality}}"></div>
        </div>   
        <div class="eight wide column">

        </div>
    </div>
    
    </div>
    <div class="row">
    <h5 class="ui header blue aligned center">Rs. {{art.price|intcomma}}</h5>
    </div>
    
    </div>
                
      </div>
     </div>
 

src/client/templates/client/client-dashboard.html
{% extends 'base.html' %}
{% load humanize %}
{% block css %}
#social__container{
    position:relative;
}
#social__icons{
    position:absolute;
    bottom:10%;
}
{% comment %} #m-small-top{
    margin-top:2rem;
} {% endcomment %}
#profile__img{
    border-radius:50%;
}
{% endblock css %}
{% block title %}
{{request.user}}-dashboard
{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="row">
        <div class="ui three wide right floated column">
             <a class="ui button primary" href="{% url 'client:client-update' %}">
             <i class="edit outline icon"></i>
             Update Profile
             </a>
        </div>
    </div>
</div>

<div class="ui grid ">
    <div class="ui two column row horizontal segments">
        <div class="ui column segment">
            <div class="ui  grid ">
                {% comment %} for left postion of profile {% endcomment %}
                <div class="ui two column row">
                {% comment %} for image of profile {% endcomment %}
                    <div class="column">
                        <div class="ui grid">
                        <div class=" column three wide">
                        &nbsp;
                        </div>
                        <div class="ui column ten wide">
                          <svg width="168" height="168" style="">  
                            <defs>  
                            <mask id="text-mask-1" x="0" y="0" width="168" height="168">  
                                <circle cx="84" cy="84" fill="white" r="84"></circle>
                            </mask>  
                            </defs>
                            <circle cx="84" cy="84" fill="white" r="84" stroke="grey"></circle>
                            <image x="0" y="0" height="100%" preserveAspectRatio="slice" width="100%" xlink:href="{{MEDIA_URL}}{{client.profile_photo}}" mask="url(#text-mask-1)"/>  
                        </svg>
                        </div>
                        <div class=" column three wide">
                        &nbsp;
                        </div>

                        </div>
                    </div>
                    {% comment %} for basic detail  of client {% endcomment %}
                    <div class="column ">
                    <h1 class="ui header blue">{{client.first_name|truncatechars:20}} {{client.last_name|truncatechars:20}}</h1>
                    <h4 class="ui header orange"><i class="gift icon"></i>Art lover{{client.one_word_about_me}}</h4>
                    <h2 class="ui  header green"><i class="icon flag"></i>Nepal{{client.country}}</h2>
                    <h3 class="ui header blue"><a href = "mailto:{{client.user.email}}"><i class="mail outline icon"></i>{{client.user.email}}</a></h3>
                    </div>
                </div>
            </div>
        </div>
        {% comment %} for right bio and social of profile {% endcomment %}
        <div id="social__container" class="ui column segment">
        {% comment %} bio section {% endcomment %}
            <h1 class="ui centered header pink"><i class="heart icon"></i>My bio</h1>
            <h5 class="ui header centered"> {{client.bio}}</h5>
        <div id="social__icons">
                    <div class="ui grid">
                    {% comment %} test {% endcomment %}
                    {% for account in client.accounts %}
                    
                            <div class="two wide column">
                            <a href="{{account.link}}">
                            <i class="{{account.type}} icon"></i>
                            </a>
                            </div>
                            
                            {% empty %}
                            <div class="column"> <h5 class="ui header green">NO social media accounts</h5></div>
                            {% endfor %}
                    </div>
        </div>    
        </div>
    </div>
    <div id="m-small-top"class="row">
    <div class="ui top attached tabular menu">
        <div class="active item">
            <button id="my-cart" class="ui button primary active"> 
                <i class="icon cart"></i>my cart
            </button>
        </div>
        <div class="item">
         <button id="my-cart" class="ui button basic primary "> 
                <i class="icon bookmark"></i>following
         </button>
        </div>

    </div>
    <div class="ui bottom attached active tab segment">
    <div class="ui container">
    <div class="ui four column grid">
        
        {% for art,artist in arts %}
        <div class="column">{% include "client/card.html" %}</div>
        
        {% empty%}
        

        {% endfor %}
        </div>
    </div>
        
    </div>
    <div class="ui bottom attached  tab segment">
        {% for artist in client.following  %}
        
        {% empty %}

        {% endfor %}
    </div>
    </div>
    <div class="row">
    </div>

{% endblock content %}

{% block scripts %}
<script>
$(document).ready(function(){
    $(".rating").rating("disable");
    
    $("#grid").css({
        "margin-left":"0px",
        "margin-right":"0px",
        "margin-top":"5px",
        "margin-bottom":"5px"
        });
    $(".ui.label:last-child ").css({"margin-right":"-1rem"});
});
</script>

{% endblock scripts %}

src/client/templates/client/client-profile.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'client/clientProfile/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'new-navbar.css' %}">  
    <link rel="stylesheet" href="{% static 'style.css' %}">  
    <title>My profile</title>
</head>
<body>
{% include "main/new-navbar.html" %}
<section style="padding-top:80px;" class="profile">
  <header class="header">
    <div class="details">
      <a class="ui button primary" href="{% url 'client:client-update' %}">
      <img src="{{MEDIA_URL}}{{client.profile_photo}}" alt="John Doe" class="profile-pic">
      </a>
      <h1 class="heading">{{request.user|truncatechars:20|title}}</h1>
      <div class="location">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
            <path d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12 ,2Z"></path>
        </svg>
        <p>Kathmandu, Nepal</p>
      </div>
      <div class="stats">
        <div class="col-4">
          <h4>{{total_cart_arts|intcomma}}</h4>
          <p>Total Arts in Cart</p>
        </div>
        <div class="col-4">
          <h4>{{client.date_updated|naturalday}}</h4>
          <p>Profile Updated</p>
        </div>
        <div class="col-4">
          <h4>{{client.date_created|naturalday}}</h4>
          <p>Profile Created</p>
        </div>
      </div>
      <div class="bio">
      <p>
      {{client.bio|truncatechars:200|lower}}
      </p>
      <h4>Bio</h4>
      </div>
    </div>
  </header>
</section> 
<script src="{% static 'main.js' %}"></script>  
</body>
</html>

src/client/templates/client/not-found.html
{% extends 'base.html' %}

{% block title %}
404 - not found
{% endblock title %}

{% block content %}
<div class="ui container">
<h1>{{error}}</h1>
</div>
{% endblock content %}