src/artGallery/urls.py
from django.urls import path
from .views import home, add_to_cart, art_detail
app_name = "artGallery"
urlpatterns = [
    path("", home, name="home"),
    path("add-to-cart", add_to_cart, name="add-to-cart"),
    path("art-detail/<int:art_id>", art_detail, name="art-detail")

]

src/cart/urls.py
from django.urls import path
from .views import view_art_gallery_cart, exhibition_cart, choose_cart
app_name = "cart"
urlpatterns = [
    path("", choose_cart, name="cart"),
    path("exhibition-cart", exhibition_cart, name="exhibition-cart"),
    path("art-gallery-cart", view_art_gallery_cart, name="art-gallery-cart")
]

src/client/urls.py
from django.urls import path
from .views import dashboard, update_client_or_artist, add_art, profile, client_profile, artist_profile, view_artist_profile
app_name = "client"
urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("client-update", update_client_or_artist, name="client-update"),
    path("add-art", add_art, name="add-art"),
    path("client-profile", client_profile, name="client-profile"),
    path("artist-profile", artist_profile, name="artist-profile"),
    path("view-artist-profile/<str:artist_id>",
         view_artist_profile, name="view-artist-profile"),
    path("profile", profile, name="profile")
]

src/exhibition/urls.py
from os import name
from django.urls import path

from artGallery.models import art
from exhibition.models import auction
from .views import exhibition_hall, add_art, art_showcase, approve_art, auction, add_exhibition, manage_exhibition, activate_exhibition, deactivate_exhibition
app_name = "exhibition"
urlpatterns = [
    path("", exhibition_hall, name="exhibition-hall"),
    path("add-art", add_art, name="add-art"),
    path("art-showcase/<int:art_id>", art_showcase, name="art-showcase"),
    path("approve-art", approve_art, name="approve-art"),
    path("auction", auction, name="auction"),
    path("add-exhibition", add_exhibition, name="add-exhibition"),
    path("manage-exhibition", manage_exhibition, name="manage-exhibition"),
    path("activate-exhibition", activate_exhibition, name="activate-exhibition"),
    path("deactivate-exhibition", deactivate_exhibition,
         name="deactivate-exhibition")
]

src/online_art_gallery/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from .view import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home_view, name="home"),
    # for signup and login feature
    path("authentication/", include("authentication.urls")),
    # for artGallery
    path("artgallery/", include("artGallery.urls")),
    path("dashboard/", include(("client.urls"))),
    path("exhibition/", include("exhibition.urls")),
    path("search/", include("search.urls"),),
    path("cart/", include("cart.urls")),

]

# this make the static file to load when were they are requested from url
urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/search/urls.py
from django.contrib.postgres import search
from django.urls import path
from .views import search_art
app_name = "search"
urlpatterns = [
    path("", search_art, name="search-art"),
]

src/templates/main/home.html
{% extends 'base.html' %}

{% block title %}
home
{% endblock title %}

{% block content %}
<p>
{{hello}}
<p>
<p>

{{user}}
<p>
{% endblock content %}

{% block scripts %}
<script >
console.log("home is working");
</script>
{% endblock scripts %}

src/templates/main/mynavbar.html
{% load humanize %}
<div id="my-nav" class="ui inverted green top fixed menu">

    
   <div class="ui text container">
        <div class="item">
        <a href="{% url 'artGallery:home' %}">Home</a>
        </div>
        <div class="item">
        <a href="{% url 'search:search-art' %}">Search</a>
        </div>
        {% if request.user.is_authenticated %}

        <div class="item">
        <a href="{% url 'exhibition:exhibition-hall' %}">Exhibition</a>
        </div>
        <div class="item">
        <a href="{% url 'client:dashboard' %}">My Dashboard</a>
        </div>
        <div class="right menu">
        <div class="item">
        <i class="icon user circle white large"></i>{{request.user|title}}
        </div>
        <div class="item">
        <a href="{% url 'authentication:logout' %}">Logout</a>
        </div>
        </div>
    

        {% endif %}

    {% if not request.user.is_authenticated%}
    <div class="right menu">
    <div class="item">
    <a href="{% url 'authentication:login' %}">Log In</a>
    </div>
    <div class="item">
    <a href="{% url 'authentication:signup' %}">Sign Up</a>
    </div>
    </div>
    {% endif %}

    </div>
</div>

src/templates/main/navbar.html
<div class="ui inverted menu">
  <div class="ui container">
    <a href="" class="item">
        <h3>OnlineAG<h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="" class="item">
        Home
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="" class="item">
                        All Profiles
                    </a>
                    <a href="" class="item">
                        Send Invites
                    </a>
                    <a href="" class="item">
                        Received Invites
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>
        
            <a href="" class="item">
                 {{ request.user }}
            </a>

            <a href="" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="" class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>

src/templates/main/new-navbar.html
{% load static %}
<div style="position: fixed; top: 0;"id="navbar">
<header class="mainHeader">
        <div class="logo" style="height:100%;">
            <a href="{% url 'artGallery:home' %}"><img style="height:100%;"src="{% static 'logo.png' %}" alt="" srcset=""></a>
        </div>
        <input type="checkbox" class="menuBtn" id="menuBtn">
            <label for="menuBtn" class="menuIcon">
                <span class="menuIconLine"></span>
            </label>
        <ul class="navLinks">
            {% if not request.user.is_superuser %}
            <li class="navLink">
                <a href="{% url 'artGallery:home' %}">HOME</a>
            </li>
            <li class="navLink">
                <a href="{% url 'search:search-art' %}">SEARCH</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="navLink">
                <a href="{% url 'client:profile' %}">PROFILE</a>
            </li>
            <li class="navLink">
                <a href="{% url 'cart:cart' %}">CART</a>
            </li>
            {% endif %}

            {% endif %}
            {% if request.user.is_authenticated %}
            <li class="navLink">
                <a href="{% url 'exhibition:exhibition-hall' %}">EXHIBITION</a>
            </li>
            {% endif %}
            {% if not request.user.is_authenticated %}
             <li class="navLink">
                <a href="{% url 'authentication:login' %}">LOGIN</a>
            </li>
           {% else %}
            <li class="navLink">
                <a href="{% url 'authentication:logout' %}">LOGOUT</a>
            </li>
            {% endif %}
        </ul>
    
    </header>
  
</div>