src/cart/urls.py
from django.urls import path
from .views import view_art_gallery_cart, exhibition_cart, choose_cart
app_name = "cart"
urlpatterns = [
    path("", choose_cart, name="cart"),
    path("exhibition-cart", exhibition_cart, name="exhibition-cart"),
    path("art-gallery-cart", view_art_gallery_cart, name="art-gallery-cart")
]

src/client/urls.py
from django.urls import path
from .views import dashboard, update_client_or_artist, add_art, profile, client_profile, artist_profile, view_artist_profile
app_name = "client"
urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("client-update", update_client_or_artist, name="client-update"),
    path("add-art", add_art, name="add-art"),
    path("client-profile", client_profile, name="client-profile"),
    path("artist-profile", artist_profile, name="artist-profile"),
    path("view-artist-profile/<str:artist_id>",
         view_artist_profile, name="view-artist-profile"),
    path("profile", profile, name="profile")
]

src/exhibition/urls.py
from os import name
from django.urls import path

from artGallery.models import art
from exhibition.models import auction
from .views import exhibition_hall, add_art, art_showcase, approve_art, auction, add_exhibition, manage_exhibition, activate_exhibition, deactivate_exhibition
app_name = "exhibition"
urlpatterns = [
    path("", exhibition_hall, name="exhibition-hall"),
    path("add-art", add_art, name="add-art"),
    path("art-showcase/<int:art_id>", art_showcase, name="art-showcase"),
    path("approve-art", approve_art, name="approve-art"),
    path("auction", auction, name="auction"),
    path("add-exhibition", add_exhibition, name="add-exhibition"),
    path("manage-exhibition", manage_exhibition, name="manage-exhibition"),
    path("activate-exhibition", activate_exhibition, name="activate-exhibition"),
    path("deactivate-exhibition", deactivate_exhibition,
         name="deactivate-exhibition")
]

src/online_art_gallery/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from .view import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home_view, name="home"),
    # for signup and login feature
    path("authentication/", include("authentication.urls")),
    # for artGallery
    path("artgallery/", include("artGallery.urls")),
    path("dashboard/", include(("client.urls"))),
    path("exhibition/", include("exhibition.urls")),
    path("search/", include("search.urls"),),
    path("cart/", include("cart.urls")),

]

# this make the static file to load when were they are requested from url
urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/exhibition/models.py
from django.db import models
from django.db.models.deletion import DO_NOTHING, SET_NULL
from django.db.models.expressions import F
from django.template.defaultfilters import default

from client.models import artist, client

# Create your models here.


class exhibition(models.Model):
    name = models.CharField(max_length=32, blank=False)
    is_active = models.BooleanField(default=False)
    exhibition_day = models.DateField(blank=False)
    exhibition_location = models.CharField(blank=False, max_length=32)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}-{self.date_created.strftime('%d-%m-%Y')}"


class art(models.Model):
    exhibition = models.ForeignKey(exhibition, on_delete=models.CASCADE)
    artist = models.ForeignKey(artist, on_delete=models.CASCADE)
    minimum_price = models.DecimalField(max_digits=20, decimal_places=2)
    name = models.CharField(max_length=32, blank=False)
    photo = models.ImageField(default="profile.png",
                              upload_to='exibition/photo/')
    video = models.FileField(upload_to="exibition/videos")
    description = models.CharField(max_length=200, blank=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name}-{self.date_created.strftime('%d-%m-%Y')}"


class auction(models.Model):
    art = models.ForeignKey(art, on_delete=models.CASCADE)
    client = models.ForeignKey(client, on_delete=models.CASCADE)
    bid_amount = models.DecimalField(max_digits=20, decimal_places=2)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.client.user.username}-{self.bid_amount}"

src/exhibition/forms.py
from django.forms import ModelForm
from django import forms
from django.forms.widgets import DateInput
from .models import exhibition, art, auction


class add_update_art_form(ModelForm):

    class Meta:
        model = art
        fields = ["name", "photo", "video", "description", "minimum_price"]


class add_update_exhibition_form(ModelForm):

    class Meta:
        model = exhibition
        fields = ["name", "exhibition_day", "exhibition_location"]

src/exhibition/views.py
from django.http import request
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from .forms import add_update_art_form, add_update_exhibition_form
from client.models import client, artist
from .models import exhibition, art, auction as auc
from django.contrib.auth.models import User
from django.db.models import Max
from decimal import Context, Decimal
from datetime import date, datetime
# Create your views here.


def can_bid():
    """
    this function help to make the bidding only on particular day
    """
    ex = exhibition.objects.filter(is_active=True).first()
    if(ex):
        ex_day = datetime.strptime(str(ex.exhibition_day), '%Y-%m-%d').date()
        return date.today() == ex_day
    else:
        return False


def exhibition_hall(request):
    can_bid()
    """
    This function is home for the exhibition hall
    """
    ex = exhibition.objects.filter(is_active=True).first()

    if(ex):
        is_exhibition = True
    else:
        is_exhibition = False
    if not request.user.is_authenticated:
        return render(request, "exhibition/not-found.html", {
            "error": "you must login first"
        })
    # is artist or not
    if(artist.objects.filter(user=request.user).first()):
        is_artist = True
    else:
        is_artist = False
    # if admin login
    if(request.user.is_superuser):
        arts = art.objects.filter(exhibition=ex,
                                  is_approved=False).order_by('date_created')
    # if artist login
    elif artist.objects.filter(user=request.user).first():
        arts = art.objects.filter(exhibition=ex,
                                  artist=artist.objects.filter(user=request.user).first())

    else:
        #  if client logined
        arts = art.objects.filter(exhibition=ex, is_approved=True)
    context = {
        "arts": arts,
        "is_artist": is_artist,
        "is_exhibition": is_exhibition,
        "exhibition": ex
    }
    return render(request, "exhibition/exhibition-hall.html", context)


def add_art(request):
    ex = exhibition.objects.filter(is_active=True).first()
    current_artist = artist.objects.filter(user=request.user).first()
    if(current_artist):
        form = add_update_art_form()
        if request.method == "POST":
            form = add_update_art_form(request.POST, request.FILES)
            current_art = form.save(commit=False)
            current_art.exhibition = ex
            current_art.artist = current_artist
            current_art.save()
            return redirect("exhibition:exhibition-hall")
        context = {
            "form": form
        }
        return render(request, "exhibition/add-update-art.html", context)

    else:
        return render(request, "exhibition/not-found.html", {"error": "this feature is only available to artist"})


def art_showcase(request, art_id):
    ex = exhibition.objects.filter(is_active=True).first()
    if not request.user.is_authenticated:
        return render(request, "exhibition/not-found.html", {
            "error": "you must login first"
        })
    current_art = art.objects.filter(exhibition=ex, id=art_id).first()
    top_5_auctions = auc.objects.filter(
        art=current_art).order_by("-bid_amount")[:5]
    if(client.objects.filter(user=request.user)):
        is_client = True
    else:
        is_client = False
    context = {
        "art": current_art,
        "is_client": is_client,
        "top_5_auctions": top_5_auctions,
        "can_bid": can_bid()
    }
    return render(request, "exhibition/art-showcase-modified.html", context)


def approve_art(request):
    ex = exhibition.objects.filter(is_active=True).first()
    if(request.user.is_superuser and request.method == "POST"):
        art_id = request.POST.get('art_id')
        art_obj = art.objects.filter(exhibition=ex, id=art_id).first()
        art_obj.is_approved = True
        art_obj.save()
        return redirect("exhibition:exhibition-hall")
    else:
        return render(request, "exhibition/not-found.html", {
            "error": "you are not the adminstrator user"
        })


def auction(request):
    if(not can_bid()):
        return render(request, "exhibition/not-found.html", {
            "error": "You can bid only in exhibition day"
        })
    if not request.user.is_authenticated:
        return render(request, "exhibition/not-found.html", {
            "error": "you must login first"
        })
    current_client = client.objects.filter(user=request.user).first()
    if(current_client and request.method == "POST"):
        bid_amount = request.POST.get('bid_amount')
        art_id = request.POST.get('art_id')
        current_art = art.objects.filter(id=art_id).first()
        max_bid = auc.objects.filter(
            art=current_art).aggregate(Max('bid_amount'))["bid_amount__max"]
        if(max_bid):
            if (Decimal(bid_amount) > Decimal(current_art.minimum_price)):
                auc.objects.create(
                    art=current_art, client=current_client, bid_amount=Decimal(bid_amount))
                current_art.minimum_price = Decimal(bid_amount)
                current_art.save()
            else:
                return render(request, "exhibition/not-found.html", {
                    "error": "you must increase bid than current bid"
                })

        elif Decimal(bid_amount) > current_art.minimum_price:
            auc.objects.create(
                art=current_art, client=current_client, bid_amount=Decimal(bid_amount))
            current_art.minimum_price = Decimal(bid_amount)
            current_art.save()

        else:
            return render(request, "exhibition/not-found.html", {
                "error": "you must increase bid than current bid"
            })

    return redirect("exhibition:art-showcase", art_id)


def add_exhibition(request):
    if(request.user.is_superuser):
        form = add_update_exhibition_form()
        if(request.method == "POST"):
            form = add_update_exhibition_form(request.POST)
            form.save()
            return redirect("exhibition:manage-exhibition")
        context = {
            "form": form
        }
        return render(request, "exhibition/add-update-exhibition.html", context)
    else:
        return render(request, "exhibition/not-found.html", {
            "error": "you must be administrator for adding exhibition"
        })


def manage_exhibition(request):
    if(request.user.is_superuser):
        exhibitions = exhibition.objects.all()
        context = {
            "exhibitions": exhibitions,
        }
        return render(request, "exhibition/manage-exhibition.html", context)
    else:
        return render(request, "exhibition/not-found.html", {
            "error": "you must be super user to manage the exhibition"
        })


def activate_exhibition(request):
    if(request.user.is_superuser and request.method == "POST"):
        exhibition_id = request.POST.get("exhibition_id")
        current_exhibition = exhibition.objects.filter(
            id=exhibition_id).first()
        if(current_exhibition):
            current_exhibition.is_active = True
            current_exhibition.save()
            exhibition.objects.exclude(
                id=exhibition_id).update(is_active=False)
            return redirect("exhibition:manage-exhibition")
    else:
        return render(request, "exhibition/not-found.html", {
            "error": "you must be administrator for adding exhibition"
        })


def deactivate_exhibition(request):
    if(request.user.is_superuser and request.method == "POST"):
        exhibition_id = request.POST.get("exhibition_id")
        current_exhibition = exhibition.objects.filter(
            id=exhibition_id).first()
        if(current_exhibition):
            current_exhibition.is_active = False
            current_exhibition.save()
        return redirect("exhibition:manage-exhibition")
    else:
        return render(request, "exhibition/not-found.html", {
            "error": "you must be administrator for adding exhibition"
        })

src/exhibition/templates/exhibition/add-update-art.html
{% extends 'base.html' %}

{% block content %}
<div class="ui container">
<form class="ui form"action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
{{form}}
<button class="ui button primary" type="submit">Add art</button>
</form>
</div>

{% endblock content %}

src/exhibition/templates/exhibition/add-update-exhibition.html
{% extends 'base.html' %}

{% block content %}
<div class="ui container">
<form class="ui form"action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
{{form}}
<button class="ui button primary" type="submit">Add art</button>
</form>
</div>

{% endblock content %}

src/exhibition/templates/exhibition/art-showcase-modified.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'exhibition/artShowcaseModified/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'new-navbar.css' %}">
    <title>Art showcase</title>
    
</head>
<body>
    {% include "main/new-navbar.html" %}
    <div id="art-showcase" style="padding-top:70px;">
    
    <div class="artist-detail">
  <a class="artist-photo-container" href="{% url 'client:view-artist-profile' art.artist.user %}">
    <img class="artist-image" src="{{MEDIA_URL}}{{art.artist.profile_photo}}" art="artis-image">
  </a>
  <div class="art-detail">
    <h2 class="artist-name"><span class="art-by">Art By </span><span class="name">{{art.artist.user|title}}</span></h2>
  </div>
</div>
<div class="image-container">
  <img class="art-image" src="{{MEDIA_URL}}{{art.photo}}" alt="art image">
</div>
<p class="art-name"><span>{{art.name|title}}</span>
</p>

<section class="horizontal-divider">
  <svg class="editorial" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28 " preserveAspectRatio="none">
    <defs>
      <path id="gentle-wave" d="M-160 44c30 0 
    58-18 88-18s
    58 18 88 18 
    58-18 88-18 
    58 18 88 18
    v44h-352z" />
    </defs>
    <g class="parallax1">
      <use xlink:href="#gentle-wave" x="50" y="3" fill="#f461c1" />
    </g>
    <g class="parallax2">
      <use xlink:href="#gentle-wave" x="50" y="0" fill="#4579e2" />
    </g>
    <g class="parallax3">
      <use xlink:href="#gentle-wave" x="50" y="9" fill="#3461c1" />
    </g>
    <g class="parallax4">
      <use xlink:href="#gentle-wave" x="50" y="6" fill="#ffffff00" />
    </g>
  </svg>
</section>
<div class="more-detail">
  <video class="art-video" controls autoplay>

    <source src="{{MEDIA_URL}}{{art.video}}" type="video/webm">

    <source src="{{MEDIA_URL}}{{art.video}}" type="video/mp4">

    Sorry, your browser doesn't support embedded videos.
  </video>
  <div class="art-description">
  {{art.description}}
  </div>
</div>
<div class="minimum-bid">
  <div class="bid-message">
    Minimum Bid
  </div>
  <div class="bid-amount">Rs: {{art.minimum_price|intcomma}}</div>
</div>
{% if is_client and can_bid %}
<form class="bid" action="{% url 'exhibition:auction' %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="art_id" value={{art.id}}>
  <div class="form-group">
    <input type="number" name="bid_amount" step="0.01" class="form-control" id="name" required data-validation-required-message="Please enter your bid amount.">
    <span class="form-highlight"></span>
    <span class="form-bar"></span>
    <label class="float-label" for="name">Bid Amount</label>
    <p class="help-block text-danger"></p>
  </div>
  <div class="bid-button">
    <div class="svg-wrapper">
      <div>
        <svg height="60" width="320" xmlns="http://www.w3.org/2000/svg">
          <rect class="shape" height="60" width="320" />
        </svg>
      </div>
      <button type="submit" class="text" style="cursor:pointer;border:none;outline:none;background:transparent;">SUBMIT</button>
    </div>
  </div>
</form>
{% endif %}
{% if top_5_auctions %}
<div class="top-five-bids">top five bids </div>
<div class="client-auction-detail">
{% for auction in top_5_auctions %}
  <div class="client-detail">
    <div class="client-photo">
      <img src="{{MEDIA_URL}}{{auction.client.profile_photo}}" alt="client image">
    </div>
    <div class="client-name">{{auction.client.user}}</div>
    <div class="auction-amount">
      RS. {{auction.bid_amount|intword}}
    </div>
  </div>
{% endfor %}
{% endif %}
{% if request.user.is_superuser %}
<form  class="bid" action="{% url 'exhibition:approve-art' %}" method="POST">
{% csrf_token %}
            <input type="hidden" name="art_id" value={{art.id}}>
<div style="margin:5rem auto;" class="bid-button">
    <div class="svg-wrapper">
      <div>
        <svg height="60" width="320" xmlns="http://www.w3.org/2000/svg">
          <rect class="shape" height="60" width="320" />
        </svg>
      </div>
      <button type="submit" class="text" style="cursor:pointer;border:none;outline:none;background:transparent;">Approve</button>
    </div>
  </div>
</form>
{% endif %}
</div>
</div>
<script src="{% static 'main.js' %}"></script>
</body>
</html>

src/exhibition/templates/exhibition/art-showcase.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<div class="ui container">
    <div class="ui grid two column">
        <div class="column green">
        <video  class="ui raised segment"width="100%" controls loop autoplay>
            <source src="{{MEDIA_URL}}{{art.video}}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
        <div class="ui segment raised">
        <h5 class="ui header">
        current top bid
        </h5>
        <h3 class="ui header">
        Rs. {{art.minimum_price|intcomma}}
        </h3>
        {% comment %} Top 5 bids {% endcomment %}
        {% if top_5_auctions %}
        <h1 class="ui header  aligned center">Top 5 bids</h1>
        {% endif %}
        {% for auction in top_5_auctions %}
        <div class="ui segment">
        <div class="ui grid two column">
        <div class="column">
            <img class="ui image mini circular" src="{{MEDIA_URL}}{{auction.client.profile_photo}}" alt="">
            <h5 class="ui header blue">{{auction.client.user}}</h5>
        </div>
        <div class="column">
        <h2 class="ui header pink">RS. {{auction.bid_amount|intword}}</h2>
        </div>
        </div>
        
        </div>
        
        {% endfor %}
        {% if request.user.is_superuser %}
        <div class="ui raised segment">
        
            <form action="{% url 'exhibition:approve-art' %}" method="POST" class='like-form' id='{{art.id}}'>
            {% csrf_token %}
            <input type="hidden" name="art_id" value={{art.id}}>
            <button type="submit" class="ui button">
            Appprove
            </button>
            </form>
        
         </div>
        {% endif %}
        </div>
        </div>
        <div  class="column">
            {% if is_client %}
            <form class="ui form" action="{% url 'exhibition:auction' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="art_id" value={{art.id}}>
                <div class="ui grid two column container">
                <div class="column">
                    <input type="number" name="bid_amount" step="0.01" required="" id="id_minimum_price">
                </div>
                <div class="column">
                    <button type="submit" style="width:50%;" class="ui button primary fluid">
                    Bid
                    </button>
                </div>
            </div>
            </form>
            {% endif %}
            <div class="ui segment">
            
            <h2  class="ui header green center aligned">
            {{art.name|truncatechars:20}}
            </h2>
            <div class="ui  segment">
                <h3 class="ui header">Detail</h3>
                <h5 class="ui header">
                {{art.description|truncatechars:50}}
                </h5>
            </div>
            <div class="ui segment">
            <div class="ui grid two column">
            <div class="column">
            <h3 class="ui header">
            Art by
            </h3>
                <div class="ui grid two column">
                    <div class="column">
                         <img class="ui image tiny circular" src="{{MEDIA_URL}}{{art.artist.profile_photo}}" alt="loading" srcset="">
                    </div>
                    <div class="column">
                        <h5 class="ui header green">{{art.artist.user}} {{art.artist.last_name}}</h5>
                    </div>
                </div>
            </div>
            </div>
            </div>
            </div>
        </div>
    </div>

</div>

{% endblock content %}

src/exhibition/templates/exhibition/exhibition-hall.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block custom-css %}
<link rel="stylesheet" href="{% static 'artGallery/css/main.css' %}">  
{% endblock custom-css %}


{% block content %}
<div class="ui container">
{% if is_artist and is_exhibition %}
<a class="ui button primary" href="{% url 'exhibition:add-art' %}">Add Art</a>
{% endif %}
{% if not is_exhibition %}
<h1 class="ui header blue aligned center">No exhibition currently availbale</h1>
{% endif %}
{% if request.user.is_superuser %}
<a class="ui button primary" href="{% url 'exhibition:manage-exhibition' %}">Manage Exhibition hall</a>
{% endif %}
</div>
<br>
<div class="ui container">
<div id="exhibition-day-container">
  Auction Day: {{exhibition.exhibition_day|naturalday}}
</div>
<div id="app" class="container">
{% for art in arts %}
        <a href="{% url 'exhibition:art-showcase' art.id %}">
            <card data-image="{{MEDIA_URL}}{{art.photo}}">
                <h1 slot="header">{{art.name|truncatechars:6|title}}</h1>
                <p slot="content">{{art.description|truncatechars:20|lower}}</p>
            </card>
        </a>
{% endfor %}
</div>
</div>
{% endblock content %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.0.1/vue.min.js"></script>
<script src="{% static 'artGallery/js/main.js' %}"></script>  
{% endblock scripts %}

src/exhibition/templates/exhibition/manage-exhibition.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<div class="ui container">
<a class="ui button primary" href="{% url 'exhibition:add-exhibition' %}">Add exhibition</a>
</div>
<br>
<br>
<div class="ui container">
<div class="ui three column grid">
{% for exhibition in exhibitions  %}
<div class="column">
    <div style="width:80%;"class="ui segment raised">
    <h2 class="ui header aligned center">
    {{exhibition.name|truncatechars:20}}
    </h2>

    <div class="ui segment">
    <h5 class="ui header green">
    <i class="map outline icon"></i>
    {{exhibition.exhibition_location|truncatechars:20}}
    </h5>
    </div>
    <div class="ui segment">
    <h5 class="ui header green">
    <i class="calendar outline icon"></i>
    {{exhibition.exhibition_day|naturalday}}
    </h5>
    </div>
    <div class="ui segment">
    {% if exhibition.is_active %}
    <div class="ui grid two column">
    <div class="column">
    <button class=" ui button green disabled">Activated</button>
    </div>
    <div class="column">
    <form action="{% url 'exhibition:deactivate-exhibition' %}" method="POST" class='like-form' id='{{art.id}}'>
            {% csrf_token %}
            <input type="hidden" name="exhibition_id" value={{exhibition.id}}>
            <button type="submit" class="ui button">
            Deactivate
            </button>
    </form>
    </div>

    
    </div>
    
    
    {% else %}
    <form action="{% url 'exhibition:activate-exhibition' %}" method="POST" class='like-form' id='{{art.id}}'>
            {% csrf_token %}
            <input type="hidden" name="exhibition_id" value={{exhibition.id}}>
            <button type="submit" class="ui button">
            Activate
            </button>
    </form>

    {% endif %}
    </div>
</div>

</div>
{% endfor %}
</div>
{% endblock content %}

src/exhibition/templates/exhibition/not-found.html
{% extends 'base.html' %}

{% block title %}

404 - not found
{% endblock title %}

{% block content %}
<div class="ui container">
<h1 class="ui header red">{{error}}</h1>
</div>

{% endblock content %}