src/artGallery/urls.py
from django.urls import path
from .views import home, add_to_cart, art_detail
app_name = "artGallery"
urlpatterns = [
    path("", home, name="home"),
    path("add-to-cart", add_to_cart, name="add-to-cart"),
    path("art-detail/<int:art_id>", art_detail, name="art-detail")

]

src/cart/urls.py
from django.urls import path
from .views import view_art_gallery_cart, exhibition_cart, choose_cart
app_name = "cart"
urlpatterns = [
    path("", choose_cart, name="cart"),
    path("exhibition-cart", exhibition_cart, name="exhibition-cart"),
    path("art-gallery-cart", view_art_gallery_cart, name="art-gallery-cart")
]

src/client/urls.py
from django.urls import path
from .views import dashboard, update_client_or_artist, add_art, profile, client_profile, artist_profile, view_artist_profile
app_name = "client"
urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("client-update", update_client_or_artist, name="client-update"),
    path("add-art", add_art, name="add-art"),
    path("client-profile", client_profile, name="client-profile"),
    path("artist-profile", artist_profile, name="artist-profile"),
    path("view-artist-profile/<str:artist_id>",
         view_artist_profile, name="view-artist-profile"),
    path("profile", profile, name="profile")
]

src/online_art_gallery/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from .view import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home_view, name="home"),
    # for signup and login feature
    path("authentication/", include("authentication.urls")),
    # for artGallery
    path("artgallery/", include("artGallery.urls")),
    path("dashboard/", include(("client.urls"))),
    path("exhibition/", include("exhibition.urls")),
    path("search/", include("search.urls"),),
    path("cart/", include("cart.urls")),

]

# this make the static file to load when were they are requested from url
urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/artGallery/models.py
from django.db import models
from utils.randomCode.getRandomCode import get_random_code
from django.template.defaultfilters import slugify
# Create your models here.


rating_choise = [(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]


class art(models.Model):
    art_name = models.CharField(max_length=200, blank=False)
    quality = models.IntegerField(choices=rating_choise, default=1)
    price = models.DecimalField(decimal_places=2, max_digits=20, blank=False)
    description = models.CharField(max_length=200, blank=False)
    art_slug = models.SlugField(
        unique=True, null=True, blank=True, editable=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    photo1 = models.ImageField(
        upload_to="photos/", blank=False)
    photo2 = models.ImageField(
        upload_to="photos/", blank=False)
    photo3 = models.ImageField(
        upload_to="photos/", blank=False)
    photo4 = models.ImageField(
        upload_to="photos/", blank=False)
    photo5 = models.ImageField(
        upload_to="photos/", blank=False)

    def __str__(self):
        return f"{self.art_slug}-{self.date_created.strftime('%d-%m-%y')}"

    def save(self, *args, **kwargs):
        slug = slugify(str(self.art_name))
        while(art.objects.filter(art_slug=slug).exists()):
            slug = slugify(str(self.art_name) + str(get_random_code()))

        self.art_slug = slug
        super().save(*args, **kwargs)

src/artGallery/forms.py
from django import forms
from .models import art


class art_add_or_update(forms.ModelForm):

    class Meta:
        model = art
        fields = ["art_name", "quality", "price", "description", "photo1",
                  "photo2", "photo3", "photo4", "photo5"]

src/artGallery/views.py
from django.shortcuts import redirect, render
from .models import art
from client.models import client, artist
from cart.models import cart
from django.http import HttpResponse

# Create your views here.


def home(request):
    if(not(request.user.is_authenticated) or request.user.is_superuser):
        arts = [(art, art.artist_set.all().first())
                for art in art.objects.all()]
        print(arts)
        return render(request, "artgallery/index.html", {
            "arts": arts,
        })
    else:
        client_user = client.objects.filter(user=request.user)
        arts = [(art, art.artist_set.all().first())
                for art in art.objects.all()]
        if(client_user):
            # for client user
            return render(request, "artgallery/index.html", {

                "arts": arts,
            })
        else:
            # for artist user
            current_artist = artist.objects.filter(user=request.user).first()
            arts = [(art, art.artist_set.all().first())
                    for art in current_artist.art_list.all()]
            return render(request, "artgallery/index.html", {

                "arts": arts,
            })


def art_detail(request, art_id):
    if(not(request.user.is_authenticated) or request.user.is_superuser):
        arts = [(art, art.artist_set.all().first())
                for art in art.objects.filter(id=art_id)]
        print(arts)
        return render(request, "artgallery/art-detail.html", {
            "arts": arts,
        })
    else:
        arts = [(art, art.artist_set.all().first())
                for art in art.objects.filter(id=art_id)]

        # for client user
        return render(request, "artgallery/art-detail.html", {

            "arts": arts,
        })


def add_to_cart(request):

    if(not(request.user.is_authenticated) or request.user.is_superuser):
        return render(request, "client/not-found.html", {
            "error": "Login as client first"
        })

    current_artist = artist.objects.filter(user=request.user)
    if(current_artist):
        return render(request, "client/not-found.html", {
            "error": "Login as client first"
        })

    user = request.user
    if request.method == 'POST':
        art_id = request.POST.get('art_id')
        art_obj = art.objects.get(id=art_id)
        current_client = client.objects.get(user=user)
        client_cart = current_client.mycart
        print(client_cart)
        print(current_client)

        if(client_cart):
            if art_obj not in current_client.mycart.art_list.all():
                current_client.mycart.art_list.add(art_obj)

        else:
            current_user_cart = cart()
            current_user_cart.save()
            current_user_cart.art_list.add(art_obj)
            current_client.mycart = current_user_cart
            current_client.save()

        return redirect("artGallery:home")

        # if profile in post_obj.liked.all():
        #     post_obj.liked.remove(profile)
        # else:
        #     post_obj.liked.add(profile)

        # cart, created = cart.objects.get_or_create(art_list=art_id)

        # if not created:
        #     if like.value == 'Like':
        #         like.value = 'Unlike'
        #     else:
        #         like.value = 'Like'
        # else:
        #     like.value = 'Like'

        #     post_obj.save()
        #     like.save()

src/artGallery/templates/artgallery/art-detail.html
{% load static %}
{% load humanize %}
<html lang="en" dir="ltr"><head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'artDetail/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'new-navbar.css' %}">  

  </head>
  <body>
  {% include "main/new-navbar.html" %}
  {% for art,artist in arts %}
    <div class="product-card">
    <div class="art-container">
        <div>
        <h1>{{art.art_name|truncatechars:10|title}}</h1>
        <p>{{art.date_created|naturalday}}</p>
         <p>{{art.description|naturalday}}</p>
        </div>
    
        <div class="artist-photo">
        <a href="{% url 'client:view-artist-profile' artist.user %}">
        <img src="{{MEDIA_URL}}{{artist.profile_photo}}" alt="" class="artist__img">
        </a>
        </div>
    </div>
      
      <div class="product-pic"></div>
      <div class="product-colors">
        <span class="blue active" data-color="#7ed6df" data-pic="url({{MEDIA_URL}}{{art.photo1}})"></span>
        <span class="green" data-color="#badc58" data-pic="url({{MEDIA_URL}}{{art.photo2}})"></span>
        <span class="yellow" data-color="#f9ca24" data-pic="url({{MEDIA_URL}}{{art.photo3}})"></span>
        <span class="rose" data-color="#ff7979" data-pic="url({{MEDIA_URL}}{{art.photo4}})"></span>
      </div>
      <div class="product-info">
        <div class="product-price">Rs. {{art.price}}</div>
        <form class='product-form' action="{% url 'artGallery:add-to-cart' %}" method="POST"  id='{{art.id}}'>
                            {% csrf_token %}
                            <input type="hidden" name="art_id" value={{art.id}}>

        <button class='product-button' type="submit" >
                                 Add to Cart
         </button>
          </form>
        {% comment %} <a href="#" class="product-button" style="color: rgb(249, 202, 36);">Add to Cart</a> {% endcomment %}
      </div>
      {% endfor %}
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>
    <script>
    $(document).ready(()=>{
        
        $(".product-colors span").click(function(){
        $(".product-colors span").removeClass("active");
        $(this).addClass("active");
        $("body").css("background",$(this).attr("data-color"));
        $(".product-price").css("color",$(this).attr("data-color"));
        $(".product-button").css("color",$(this).attr("data-color"));
        $(".product-pic").css("background-image",$(this).attr("data-pic"));
      });;
      setInterval(function(){ $(".product-colors .active").click(); }, 3000);
      
    });
    
      
    </script>
    <script src="{% static 'main.js' %}"></script>

</body></html>

src/artGallery/templates/artgallery/card.html
{% load humanize%}
<div id="c-card" class="ui card">
    <div id="c-card__pading"class="content">
    <img src="{{MEDIA_URL}}{{art.photo1}}" alt="" class="ui  image">
                
    <div id="c-card__top">
    <div id="margin-top-5 margin-bottom-5"><h5 class="ui header centered green label fluid">{{art.art_name|title}}</h5></div>
    <div id="grid"class="ui grid middle aligned">
    <div class="row">
        <div class="eight wide column">
        <div class="ui small star rating" data-max-rating="5" data-rating="{{art.quality}}"></div>
        </div>   
        <div class="eight wide column">
        {% if request.user.is_authenticated %}
        <form action="{% url 'artGallery:add-to-cart' %}" method="POST" class='like-form' id='{{art.id}}'>
                            {% csrf_token %}
                            <input type="hidden" name="art_id" value={{art.id}}>

                                <button type="submit" class="ui button cart">
                                 <i class="cart icon cart"></i> cart
         </button>
          </form>
        {% endif %}
         
        </div>
    </div>
    </div>
    <div style="margin-bottom: 18px;"class="row">
    <h5 class="ui header blue aligned center">Rs. {{art.price|intcomma}}</h5>
    </div>
                
    
        <div id="grid" class="ui grid middle aligned label white">
                        <div class="eight wide column">
                        <h5 class="ui header blue">{{artist.user|title}}</h5>
                        </div>
                            
                        <div class="eight wide column ">
                                <img class="ui image circular tiny"src="{{MEDIA_URL}}{{artist.profile_photo}}" alt="">
                        </div>

        </div>
                
      </div>
     </div>
 </div>

src/artGallery/templates/artgallery/index.html
{% load static %}
{% load humanize %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'artGallery/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'new-navbar.css' %}">  
    <link rel="stylesheet" href="{% static 'style.css' %}">  


    <title>Home</title>

</head>
<body>
{% include "main/new-navbar.html" %}
<div style="paddin-top:80px;" id="app" class="container">
{% for art,artist in arts %}
        <a href="{% url 'artGallery:art-detail' art.id %}">
            <card data-image="{{MEDIA_URL}}{{art.photo1}}">
                <h1 slot="header">{{art.art_name|truncatechars:6|title}}</h1>
                <p slot="content">{{art.description|truncatechars:20|lower}}</p>
            </card>
        </a>
{% endfor %}
</div>
</div>




<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.0.1/vue.min.js"></script>
<script src="{% static 'artGallery/js/main.js' %}"></script>
<script src="{% static 'main.js' %}"></script>  


</body>
</html>